Correct spelling mistakes

diff --git a/location-tracker/mvnw b/location-tracker/mvnw
--- a/location-tracker/mvnw
+++ b/location-tracker/mvnw
@@ -150,4 +150,9 @@ if [ -z "$JAVACMD" ] ; then
 fi
 
 if [ ! -x "$JAVACMD" ] ; then
-  ech
+  echo "Error: JAVA_HOME is not defined correctly." >&2
+  echo "  We cannot execute $JAVACMD" >&2
+  exit 1
+fi
+
+if [ -z "$JAVA_HOME" ] ; then
