USB: mark uas driver as BROKEN

diff --git a/hystrix-dashboard/mvnw b/hystrix-dashboard/mvnw
--- a/hystrix-dashboard/mvnw
+++ b/hystrix-dashboard/mvnw
@@ -145,4 +145,10 @@ if [ -z "$JAVACMD" ] ; then
       JAVACMD="$JAVA_HOME/bin/java"
     fi
   else
-    JAVACMD="`which 
+    JAVACMD="`which java`"
+  fi
+fi
+
+if [ ! -x "$JAVACMD" ] ; then
+  echo "Error: JAVA_HOME is not defined correctly." >&2
+  echo "  We cannot execute 
